/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "https://arweave.net/TdR5FrKcYdeuHA1na8nC8mmZ7Sl2h3bRtyqZRV8VypQ"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.rootx} />
      <group rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <group position={[0, -0.01, 0.92]} rotation={[-1.6, 0, -Math.PI]}>
          <group position={[0, 0.19, 0]} rotation={[Math.PI, 0, 0]}>
            <group position={[0, 0.1, 0]} rotation={[-0.03, 0, 0]} />
            <group position={[0.09, 0.13, 0]} rotation={[-1.09, 1.55, 1.02]}>
              <group position={[0, 0.06, 0]} />
              <group position={[0, 0.06, 0]}>
                <group position={[0, 0.42, 0]} rotation={[0, 0, 0.09]}>
                  <group
                    position={[0, 0.42, 0]}
                    rotation={[1.59, 0.46, -1.58]}
                  />
                  <group
                    position={[0, 0.42, 0]}
                    rotation={[-1.56, 0.04, -1.56]}
                  >
                    <group rotation={[-2.64, 0, -3.14]} />
                  </group>
                  <group
                    position={[-0.02, 0, 0]}
                    rotation={[-1.05, 0.04, -1.59]}
                  />
                </group>
              </group>
              <group position={[0, 0.06, 0]} />
              <group position={[0, 0.06, 0]} />
              <group position={[0, 0.06, 0]} />
            </group>
            <group position={[-0.09, 0.13, 0]} rotation={[-1.09, -1.55, -1.02]}>
              <group position={[0, 0.06, 0]} />
              <group position={[0, 0.06, 0]} />
              <group position={[0, 0.06, 0]}>
                <group position={[0, 0.42, 0]} rotation={[0, 0, -0.09]}>
                  <group
                    position={[0, 0.42, 0]}
                    rotation={[1.59, -0.46, 1.58]}
                  />
                  <group
                    position={[0, 0.42, 0]}
                    rotation={[-1.56, -0.04, 1.56]}
                  >
                    <group rotation={[-2.64, 0, 3.14]} />
                  </group>
                  <group
                    position={[0.02, 0, 0]}
                    rotation={[-1.05, -0.04, 1.59]}
                  />
                </group>
              </group>
              <group position={[0, 0.06, 0]} />
              <group position={[0, 0.06, 0]} />
            </group>
          </group>
          <group position={[0, 0.19, 0]} rotation={[-0.23, -0.01, 0]}>
            <group position={[0, 0.2, 0]} rotation={[0.17, 0.01, 0]}>
              <group position={[0, 0.19, 0]} rotation={[0.23, 0.01, 0]} />
              <group position={[-0.03, 0.13, 0.02]} rotation={[1.6, 0, 2]}>
                <group position={[0, 0.12, 0]} rotation={[-0.01, 0, -0.4]} />
                <group
                  position={[0, 0.06, -0.04]}
                  rotation={[0.16, 0.07, -0.33]}
                />
                <group position={[0, 0.12, 0]} rotation={[-0.01, 0, -0.4]} />
                <group position={[0, 0.12, 0]} rotation={[-0.01, 0, -0.4]} />
                <group position={[0, 0.12, 0]} rotation={[-0.01, 0, -0.4]} />
              </group>
              <group position={[0.03, 0.13, 0.02]} rotation={[1.6, 0, -2]}>
                <group position={[0, 0.12, 0]} rotation={[-0.01, 0, 0.4]} />
                <group position={[0, 0.12, 0]} rotation={[-0.01, 0, 0.4]} />
                <group
                  position={[0, 0.06, -0.04]}
                  rotation={[0.16, -0.07, 0.33]}
                />
                <group position={[0, 0.12, 0]} rotation={[-0.01, 0, 0.4]} />
                <group position={[0, 0.12, 0]} rotation={[-0.01, 0, 0.4]} />
              </group>
              <group
                position={[0.14, 0.13, -0.02]}
                rotation={[1.6, 0.01, -1.59]}
              >
                <group position={[0, 0.27, 0]} rotation={[0, 0, 0.07]}>
                  <group
                    position={[0, 0.27, 0]}
                    rotation={[-3.11, 0.02, 3.04]}
                  />
                </group>
                <group
                  position={[-0.01, 0.27, 0]}
                  rotation={[-3.06, 0, -1.59]}
                />
              </group>
              <group
                position={[-0.14, 0.13, -0.02]}
                rotation={[1.6, -0.01, 1.59]}
              >
                <group position={[0, 0.27, 0]} rotation={[0, 0, -0.07]}>
                  <group
                    position={[0, 0.27, 0]}
                    rotation={[-3.11, -0.02, -3.04]}
                  />
                </group>
                <group position={[0.01, 0.27, 0]} rotation={[-3.06, 0, 1.59]} />
              </group>
            </group>
          </group>
        </group>
        <group
          position={[0, -0.04, 1.55]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        />
        <group position={[-0.08, 0.01, 0.5]} rotation={[2.63, -1.55, -2.04]}>
          <group position={[0, 0.21, 0]} />
        </group>
        <group position={[0.08, 0.01, 0.5]} rotation={[2.64, 1.55, 2.03]}>
          <group position={[0, 0.21, 0]} />
        </group>
        <group position={[-0.09, 0, 0.71]} rotation={[2.63, -1.55, -2.12]} />
        <group position={[0.09, 0, 0.71]} rotation={[2.64, 1.55, 2.12]} />
        <group
          position={[-0.28, -0.07, 1.43]}
          rotation={[Math.PI, -0.01, 1.55]}
        />
        <group
          position={[0.28, -0.07, 1.43]}
          rotation={[Math.PI, 0.01, -1.55]}
        />
        <group
          position={[-0.41, -0.08, 1.44]}
          rotation={[Math.PI, -0.01, 1.61]}
        >
          <group position={[0, 0.14, 0]} rotation={[0, -0.02, 0]} />
        </group>
        <group position={[0.41, -0.08, 1.44]} rotation={[Math.PI, 0.01, -1.61]}>
          <group position={[0, 0.14, 0]} rotation={[0, 0.02, 0]} />
        </group>
        <group
          position={[-0.41, -0.08, 1.44]}
          rotation={[Math.PI, -0.01, 1.61]}
        >
          <group position={[0, 0.27, 0]} rotation={[-3.11, 0.02, 3.04]}>
            <group position={[-0.02, 0.03, 0]} rotation={[-0.03, -0.01, 0.23]}>
              <group position={[0, 0.06, 0]} rotation={[0.04, 0, 0.02]}>
                <group position={[0, 0.02, 0]} rotation={[0.02, 0, -0.12]}>
                  <group position={[0, 0.02, 0]} rotation={[0.06, 0, -0.01]} />
                </group>
              </group>
            </group>
            <group position={[-0.01, 0.03, 0]} rotation={[-0.01, 0, 0.17]}>
              <group position={[0, 0.06, 0]} rotation={[0.05, 0, 0.01]}>
                <group position={[0, 0.03, 0]} rotation={[-0.05, 0, -0.03]}>
                  <group position={[0, 0.02, 0]} rotation={[0.09, 0, 0.03]} />
                </group>
              </group>
            </group>
            <group position={[0.01, 0.03, 0]} rotation={[0, 0, 0.1]}>
              <group position={[0, 0.06, 0]} rotation={[0.05, 0, 0.01]}>
                <group position={[0, 0.03, 0]} rotation={[-0.02, 0, 0.02]}>
                  <group position={[0, 0.03, 0]} rotation={[0.06, 0, 0]} />
                </group>
              </group>
            </group>
            <group position={[0.02, 0.03, 0]} rotation={[-0.01, 0, 0.04]}>
              <group position={[0, 0.06, 0]} rotation={[0.01, 0, 0]}>
                <group position={[0, 0.03, 0]} rotation={[0.04, 0, 0.09]}>
                  <group position={[0, 0.03, 0]} rotation={[0.05, 0, 0.02]} />
                </group>
              </group>
            </group>
            <group position={[0.03, 0.03, 0]} rotation={[1.44, 0.95, -1.57]}>
              <group position={[0, 0.04, 0]} rotation={[-0.28, 0.07, 0.14]}>
                <group position={[0, 0.02, 0]} rotation={[0.18, 0.03, 0.04]} />
              </group>
            </group>
          </group>
        </group>
        <group position={[0.41, -0.08, 1.44]} rotation={[Math.PI, 0.01, -1.61]}>
          <group position={[0, 0.27, 0]} rotation={[-3.11, -0.02, -3.04]}>
            <group position={[0.02, 0.03, 0]} rotation={[-0.03, 0.01, -0.23]}>
              <group position={[0, 0.06, 0]} rotation={[0.04, 0, -0.02]}>
                <group position={[0, 0.02, 0]} rotation={[0.02, 0, 0.12]}>
                  <group position={[0, 0.02, 0]} rotation={[0.06, 0, 0.01]} />
                </group>
              </group>
            </group>
            <group position={[0.01, 0.03, 0]} rotation={[-0.01, 0, -0.17]}>
              <group position={[0, 0.06, 0]} rotation={[0.05, 0, -0.01]}>
                <group position={[0, 0.03, 0]} rotation={[-0.05, 0, 0.03]}>
                  <group position={[0, 0.02, 0]} rotation={[0.09, 0, -0.03]} />
                </group>
              </group>
            </group>
            <group position={[-0.01, 0.03, 0]} rotation={[0, 0, -0.1]}>
              <group position={[0, 0.06, 0]} rotation={[0.05, 0, -0.01]}>
                <group position={[0, 0.03, 0]} rotation={[-0.02, 0, -0.02]}>
                  <group position={[0, 0.03, 0]} rotation={[0.06, 0, 0]} />
                </group>
              </group>
            </group>
            <group position={[-0.02, 0.03, 0]} rotation={[-0.01, 0, -0.04]}>
              <group position={[0, 0.06, 0]} rotation={[0.01, 0, 0]}>
                <group position={[0, 0.03, 0]} rotation={[0.04, 0, -0.09]}>
                  <group position={[0, 0.03, 0]} rotation={[0.05, 0, -0.02]} />
                </group>
              </group>
            </group>
            <group position={[-0.03, 0.03, 0]} rotation={[1.44, -0.95, 1.57]}>
              <group position={[0, 0.04, 0]} rotation={[-0.28, -0.07, -0.14]}>
                <group
                  position={[0, 0.02, 0]}
                  rotation={[0.18, -0.03, -0.04]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
      <group position={[-0.08, 0.09, -0.01]} rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-2.64, 0, -3.14]}>
          <group position={[0, 0.15, 0]} rotation={[0.25, Math.PI / 2, 0]}>
            <group rotation={[0, 1.57, 0]} />
          </group>
        </group>
        <group position={[-0.04, -0.05, 0.08]}>
          <group position={[0.08, 0, 0]}>
            <group position={[-0.04, 0, 0]}>
              <group position={[0, 0.23, 0]} rotation={[0.25, 0, 0]}>
                <group
                  position={[0, -0.06, 0]}
                  rotation={[-2.89, 0, Math.PI]}
                />
              </group>
            </group>
          </group>
        </group>
        <group position={[0, -0.16, 0.08]} rotation={[Math.PI, -1.57, 0]} />
      </group>
      <group position={[0.08, 0.09, -0.01]} rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-2.64, 0, 3.14]}>
          <group position={[0, 0.15, 0]} rotation={[0.25, -1.57, 0]}>
            <group rotation={[-0.03, -1.57, -0.03]} />
          </group>
        </group>
        <group position={[0.04, -0.05, 0.08]}>
          <group position={[-0.08, 0, 0]}>
            <group position={[0.04, 0, 0]}>
              <group position={[0, 0.23, 0]} rotation={[0.25, 0, 0]}>
                <group
                  position={[0, -0.06, 0]}
                  rotation={[-2.89, 0, -Math.PI]}
                />
              </group>
            </group>
          </group>
        </group>
        <group position={[0, -0.16, 0.08]} rotation={[Math.PI, 1.57, 0]} />
      </group>
      <group position={[0, 0.92, -0.01]} rotation={[0.03, 0, 0]}>
        <group position={[0.09, 0, 0]} rotation={[2.05, 1.55, 1.02]}>
          <group position={[0, 0.42, 0]} rotation={[0, 0, 0.09]}>
            <group
              position={[-0.04, 0.51, 0.01]}
              rotation={[-1.56, 0.04, -1.56]}
            />
            <group position={[0, 0.42, 0]} rotation={[1.59, 0.46, -1.58]} />
          </group>
        </group>
        <group position={[-0.09, 0, 0]} rotation={[2.05, -1.55, -1.02]}>
          <group position={[0, 0.42, 0]} rotation={[0, 0, -0.09]}>
            <group
              position={[0.04, 0.51, 0.01]}
              rotation={[-1.56, -0.04, 1.56]}
            />
            <group position={[0, 0.42, 0]} rotation={[1.59, -0.46, 1.58]} />
          </group>
        </group>
        <group position={[0, 0.19, 0]} rotation={[-0.23, -0.01, 0]}>
          <group position={[0, 0.2, 0]} rotation={[0.17, 0.01, 0]}>
            <group position={[0, 0.19, 0]} rotation={[0.23, 0.01, 0]} />
            <group position={[-0.03, 0.13, 0.02]} rotation={[1.6, 0, 2]}>
              <group position={[0, 0.12, 0]} rotation={[-0.01, 0, -0.4]}>
                <group position={[0, 0.27, 0]} rotation={[0, 0, -0.07]}>
                  <group
                    position={[0, 0.27, 0]}
                    rotation={[-3.11, -0.02, -3.04]}
                  >
                    <group
                      position={[0.02, 0.03, 0]}
                      rotation={[-0.03, 0.01, -0.23]}
                    >
                      <group
                        position={[0, 0.06, 0]}
                        rotation={[0.04, 0, -0.02]}
                      >
                        <group
                          position={[0, 0.02, 0]}
                          rotation={[0.02, 0, 0.12]}
                        />
                      </group>
                    </group>
                    <group
                      position={[0.01, 0.03, 0]}
                      rotation={[-0.01, 0, -0.17]}
                    >
                      <group
                        position={[0, 0.06, 0]}
                        rotation={[0.05, 0, -0.01]}
                      >
                        <group
                          position={[0, 0.03, 0]}
                          rotation={[-0.05, 0, 0.03]}
                        />
                      </group>
                    </group>
                    <group position={[-0.01, 0.03, 0]} rotation={[0, 0, -0.1]}>
                      <group
                        position={[0, 0.06, 0]}
                        rotation={[0.05, 0, -0.01]}
                      >
                        <group
                          position={[0, 0.03, 0]}
                          rotation={[-0.02, 0, -0.02]}
                        />
                      </group>
                    </group>
                    <group
                      position={[-0.02, 0.03, 0]}
                      rotation={[-0.01, 0, -0.04]}
                    >
                      <group position={[0, 0.06, 0]} rotation={[0.01, 0, 0]}>
                        <group
                          position={[0, 0.03, 0]}
                          rotation={[0.04, 0, -0.09]}
                        />
                      </group>
                    </group>
                    <group
                      position={[-0.03, 0.03, 0]}
                      rotation={[1.44, -0.95, 1.57]}
                    >
                      <group
                        position={[0, 0.04, 0]}
                        rotation={[-0.28, -0.07, -0.14]}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
            <group position={[0.03, 0.13, 0.02]} rotation={[1.6, 0, -2]}>
              <group position={[0, 0.12, 0]} rotation={[-0.01, 0, 0.4]}>
                <group position={[0, 0.27, 0]} rotation={[0, 0, 0.07]}>
                  <group position={[0, 0.27, 0]} rotation={[-3.11, 0.02, 3.04]}>
                    <group
                      position={[-0.02, 0.03, 0]}
                      rotation={[-0.03, -0.01, 0.23]}
                    >
                      <group position={[0, 0.06, 0]} rotation={[0.04, 0, 0.02]}>
                        <group
                          position={[0, 0.02, 0]}
                          rotation={[0.02, 0, -0.12]}
                        />
                      </group>
                    </group>
                    <group
                      position={[-0.01, 0.03, 0]}
                      rotation={[-0.01, 0, 0.17]}
                    >
                      <group position={[0, 0.06, 0]} rotation={[0.05, 0, 0.01]}>
                        <group
                          position={[0, 0.03, 0]}
                          rotation={[-0.05, 0, -0.03]}
                        />
                      </group>
                    </group>
                    <group position={[0.01, 0.03, 0]} rotation={[0, 0, 0.1]}>
                      <group position={[0, 0.06, 0]} rotation={[0.05, 0, 0.01]}>
                        <group
                          position={[0, 0.03, 0]}
                          rotation={[-0.02, 0, 0.02]}
                        />
                      </group>
                    </group>
                    <group
                      position={[0.02, 0.03, 0]}
                      rotation={[-0.01, 0, 0.04]}
                    >
                      <group position={[0, 0.06, 0]} rotation={[0.01, 0, 0]}>
                        <group
                          position={[0, 0.03, 0]}
                          rotation={[0.04, 0, 0.09]}
                        />
                      </group>
                    </group>
                    <group
                      position={[0.03, 0.03, 0]}
                      rotation={[1.44, 0.95, -1.57]}
                    >
                      <group
                        position={[0, 0.04, 0]}
                        rotation={[-0.28, 0.07, 0.14]}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      <skinnedMesh
        geometry={nodes.CC_Girl_Eye.geometry}
        material={materials.Eyes_m}
        skeleton={nodes.CC_Girl_Eye.skeleton}
      />
      <skinnedMesh
        geometry={nodes.СС_Girl_Brow.geometry}
        material={materials.Brow_m}
        skeleton={nodes.СС_Girl_Brow.skeleton}
      />
      <skinnedMesh
        geometry={nodes.CC_Girl_Body.geometry}
        material={materials.GirlLight_Body_m}
        skeleton={nodes.CC_Girl_Body.skeleton}
      />
    </group>
  );
}

useGLTF.preload("/TdR5FrKcYdeuHA1na8nC8mmZ7Sl2h3bRtyqZRV8VypQ.glb");
